name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add Env
      run: echo "${{ secrets.ENV_FILE }}" > .env
    - name: Add receiver
      run: echo "${{ secrets.RECEIVERS }}" > src/assets/receiver.yaml
    - name: Send
    - name: Build
      run: cargo build --verbose --release --all-features
    - name: Run tests
      run: cargo test --verbose
