name: Send Newsletter

on:
  schedule:
  - cron: "0 6 * * *"

jobs:
  send_newsletter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add Env
      run: echo "${{ secrets.ENV_FILE }}" > .env
    - name: Add receiver
      run: echo "${{ secrets.RECEIVERS }}" > receiver.yaml
    - name: Send
      run: cargo run
