name: Send Newsletter

on:
  schedule:
    - cron: '22 22 * * *'

jobs:
  send_newsletter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add Env
      run: echo "${{ secrets.ENV_FILE }}" > .env
    - name: Add receiver
      run: echo "${{ secrets.RECEIVERS }}" > src/assets/receiver.yaml
    - name: Send
      run: cargo run